test_that("blblm()", {
  fit <- blblm(mpg ~ wt + hp, file = mtcars, m=5, B=100, cl = 2)
  expect_s3_class(fit, "blblm")
  expect_equal(length(fit$estimates), 5)
  expect_equal(length(coef(fit)), 3)
  expect_equal(dim(confint(fit)), c(2, 2))
  splitdata <- split_data(mtcars, m=5)
  expect_equal(length(splitdata), 5)

  fit2 <- blbglm(am ~ wt + hp, file = mtcars, m=5, B=100, cl = 2)
  expect_s3_class(fit2, "blbglm")
  expect_equal(length(fit2$estimates), 5)
  expect_equal(length(coef(fit2)), 3)
  expect_equal(dim(confint(fit2)), c(2, 2))
})