# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' estimate the regression estimates based on given the number of repetitions
#' @name fast_lm
#' @param X matrix for explanatory
#' @param y column vector for response variable
#' @export fast_lm
#'
fast_lm <- function(X, y) {
    .Call('_blblm_fast_lm', PACKAGE = 'blblm', X, y)
}

